//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace RSRD
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbEntities object using the connection string found in the 'dbEntities' section of the application configuration file.
        /// </summary>
        public dbEntities() : base("name=dbEntities", "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbEntities object.
        /// </summary>
        public dbEntities(string connectionString) : base(connectionString, "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbEntities object.
        /// </summary>
        public dbEntities(EntityConnection connection) : base(connection, "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Organization> Organizations
        {
            get
            {
                if ((_Organizations == null))
                {
                    _Organizations = base.CreateObjectSet<Organization>("Organizations");
                }
                return _Organizations;
            }
        }
        private ObjectSet<Organization> _Organizations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbanimal> dbanimals
        {
            get
            {
                if ((_dbanimals == null))
                {
                    _dbanimals = base.CreateObjectSet<dbanimal>("dbanimals");
                }
                return _dbanimals;
            }
        }
        private ObjectSet<dbanimal> _dbanimals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmployeeLogin> EmployeeLogins
        {
            get
            {
                if ((_EmployeeLogins == null))
                {
                    _EmployeeLogins = base.CreateObjectSet<EmployeeLogin>("EmployeeLogins");
                }
                return _EmployeeLogins;
            }
        }
        private ObjectSet<EmployeeLogin> _EmployeeLogins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<testa> testas
        {
            get
            {
                if ((_testas == null))
                {
                    _testas = base.CreateObjectSet<testa>("testas");
                }
                return _testas;
            }
        }
        private ObjectSet<testa> _testas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbRecord> dbRecords
        {
            get
            {
                if ((_dbRecords == null))
                {
                    _dbRecords = base.CreateObjectSet<dbRecord>("dbRecords");
                }
                return _dbRecords;
            }
        }
        private ObjectSet<dbRecord> _dbRecords;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Organizations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrganizations(Organization organization)
        {
            base.AddObject("Organizations", organization);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbanimals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbanimals(dbanimal dbanimal)
        {
            base.AddObject("dbanimals", dbanimal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmployeeLogins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployeeLogins(EmployeeLogin employeeLogin)
        {
            base.AddObject("EmployeeLogins", employeeLogin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the testas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotestas(testa testa)
        {
            base.AddObject("testas", testa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbRecords(dbRecord dbRecord)
        {
            base.AddObject("dbRecords", dbRecord);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RSRD", Name="dbanimal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbanimal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbanimal object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static dbanimal Createdbanimal(global::System.Int32 id)
        {
            dbanimal dbanimal = new dbanimal();
            dbanimal.ID = id;
            return dbanimal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofBirth
        {
            get
            {
                return _DateofBirth;
            }
            set
            {
                OnDateofBirthChanging(value);
                ReportPropertyChanging("DateofBirth");
                _DateofBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofBirth");
                OnDateofBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofBirth;
        partial void OnDateofBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> dobIsEstimated
        {
            get
            {
                return _dobIsEstimated;
            }
            set
            {
                OndobIsEstimatedChanging(value);
                ReportPropertyChanging("dobIsEstimated");
                _dobIsEstimated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dobIsEstimated");
                OndobIsEstimatedChanged();
            }
        }
        private Nullable<global::System.Boolean> _dobIsEstimated;
        partial void OndobIsEstimatedChanging(Nullable<global::System.Boolean> value);
        partial void OndobIsEstimatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> vaccinationDate
        {
            get
            {
                return _vaccinationDate;
            }
            set
            {
                OnvaccinationDateChanging(value);
                ReportPropertyChanging("vaccinationDate");
                _vaccinationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vaccinationDate");
                OnvaccinationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _vaccinationDate;
        partial void OnvaccinationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnvaccinationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> sterilized
        {
            get
            {
                return _sterilized;
            }
            set
            {
                OnsterilizedChanging(value);
                ReportPropertyChanging("sterilized");
                _sterilized = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sterilized");
                OnsterilizedChanged();
            }
        }
        private Nullable<global::System.Boolean> _sterilized;
        partial void OnsterilizedChanging(Nullable<global::System.Boolean> value);
        partial void OnsterilizedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String color
        {
            get
            {
                return _color;
            }
            set
            {
                OncolorChanging(value);
                ReportPropertyChanging("color");
                _color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("color");
                OncolorChanged();
            }
        }
        private global::System.String _color;
        partial void OncolorChanging(global::System.String value);
        partial void OncolorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.String _size;
        partial void OnsizeChanging(global::System.String value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String breed
        {
            get
            {
                return _breed;
            }
            set
            {
                OnbreedChanging(value);
                ReportPropertyChanging("breed");
                _breed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("breed");
                OnbreedChanged();
            }
        }
        private global::System.String _breed;
        partial void OnbreedChanging(global::System.String value);
        partial void OnbreedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String crossbreed
        {
            get
            {
                return _crossbreed;
            }
            set
            {
                OncrossbreedChanging(value);
                ReportPropertyChanging("crossbreed");
                _crossbreed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("crossbreed");
                OncrossbreedChanged();
            }
        }
        private global::System.String _crossbreed;
        partial void OncrossbreedChanging(global::System.String value);
        partial void OncrossbreedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String owner
        {
            get
            {
                return _owner;
            }
            set
            {
                OnownerChanging(value);
                ReportPropertyChanging("owner");
                _owner = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("owner");
                OnownerChanged();
            }
        }
        private global::System.String _owner;
        partial void OnownerChanging(global::System.String value);
        partial void OnownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String species
        {
            get
            {
                return _species;
            }
            set
            {
                OnspeciesChanging(value);
                ReportPropertyChanging("species");
                _species = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("species");
                OnspeciesChanged();
            }
        }
        private global::System.String _species;
        partial void OnspeciesChanging(global::System.String value);
        partial void OnspeciesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RSRD", Name="dbRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbRecord object.
        /// </summary>
        /// <param name="recordName">Initial value of the recordName property.</param>
        public static dbRecord CreatedbRecord(global::System.String recordName)
        {
            dbRecord dbRecord = new dbRecord();
            dbRecord.recordName = recordName;
            return dbRecord;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String recordName
        {
            get
            {
                return _recordName;
            }
            set
            {
                if (_recordName != value)
                {
                    OnrecordNameChanging(value);
                    ReportPropertyChanging("recordName");
                    _recordName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("recordName");
                    OnrecordNameChanged();
                }
            }
        }
        private global::System.String _recordName;
        partial void OnrecordNameChanging(global::System.String value);
        partial void OnrecordNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String recordData
        {
            get
            {
                return _recordData;
            }
            set
            {
                OnrecordDataChanging(value);
                ReportPropertyChanging("recordData");
                _recordData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("recordData");
                OnrecordDataChanged();
            }
        }
        private global::System.String _recordData;
        partial void OnrecordDataChanging(global::System.String value);
        partial void OnrecordDataChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RSRD", Name="EmployeeLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmployeeLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmployeeLogin object.
        /// </summary>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static EmployeeLogin CreateEmployeeLogin(global::System.String username, global::System.String password)
        {
            EmployeeLogin employeeLogin = new EmployeeLogin();
            employeeLogin.username = username;
            employeeLogin.password = password;
            return employeeLogin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                if (_username != value)
                {
                    OnusernameChanging(value);
                    ReportPropertyChanging("username");
                    _username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("username");
                    OnusernameChanged();
                }
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RSRD", Name="Organization")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Organization : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Organization object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Organization CreateOrganization(global::System.Int32 id)
        {
            Organization organization = new Organization();
            organization.id = id;
            return organization;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fax
        {
            get
            {
                return _fax;
            }
            set
            {
                OnfaxChanging(value);
                ReportPropertyChanging("fax");
                _fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fax");
                OnfaxChanged();
            }
        }
        private global::System.String _fax;
        partial void OnfaxChanging(global::System.String value);
        partial void OnfaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String website
        {
            get
            {
                return _website;
            }
            set
            {
                OnwebsiteChanging(value);
                ReportPropertyChanging("website");
                _website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("website");
                OnwebsiteChanged();
            }
        }
        private global::System.String _website;
        partial void OnwebsiteChanging(global::System.String value);
        partial void OnwebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aboutus
        {
            get
            {
                return _aboutus;
            }
            set
            {
                OnaboutusChanging(value);
                ReportPropertyChanging("aboutus");
                _aboutus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aboutus");
                OnaboutusChanged();
            }
        }
        private global::System.String _aboutus;
        partial void OnaboutusChanging(global::System.String value);
        partial void OnaboutusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hours
        {
            get
            {
                return _hours;
            }
            set
            {
                OnhoursChanging(value);
                ReportPropertyChanging("hours");
                _hours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hours");
                OnhoursChanged();
            }
        }
        private global::System.String _hours;
        partial void OnhoursChanging(global::System.String value);
        partial void OnhoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String servicesprovided
        {
            get
            {
                return _servicesprovided;
            }
            set
            {
                OnservicesprovidedChanging(value);
                ReportPropertyChanging("servicesprovided");
                _servicesprovided = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("servicesprovided");
                OnservicesprovidedChanged();
            }
        }
        private global::System.String _servicesprovided;
        partial void OnservicesprovidedChanging(global::System.String value);
        partial void OnservicesprovidedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] logo
        {
            get
            {
                return StructuralObject.GetValidValue(_logo);
            }
            set
            {
                OnlogoChanging(value);
                ReportPropertyChanging("logo");
                _logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logo");
                OnlogoChanged();
            }
        }
        private global::System.Byte[] _logo;
        partial void OnlogoChanging(global::System.Byte[] value);
        partial void OnlogoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RSRD", Name="testa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class testa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new testa object.
        /// </summary>
        /// <param name="c0">Initial value of the C0 property.</param>
        /// <param name="c1">Initial value of the C1 property.</param>
        /// <param name="c2">Initial value of the C2 property.</param>
        public static testa Createtesta(global::System.String c0, global::System.Int32 c1, global::System.DateTime c2)
        {
            testa testa = new testa();
            testa.C0 = c0;
            testa.C1 = c1;
            testa.C2 = c2;
            return testa;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C0
        {
            get
            {
                return _C0;
            }
            set
            {
                if (_C0 != value)
                {
                    OnC0Changing(value);
                    ReportPropertyChanging("C0");
                    _C0 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("C0");
                    OnC0Changed();
                }
            }
        }
        private global::System.String _C0;
        partial void OnC0Changing(global::System.String value);
        partial void OnC0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C1
        {
            get
            {
                return _C1;
            }
            set
            {
                OnC1Changing(value);
                ReportPropertyChanging("C1");
                _C1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C1");
                OnC1Changed();
            }
        }
        private global::System.Int32 _C1;
        partial void OnC1Changing(global::System.Int32 value);
        partial void OnC1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime C2
        {
            get
            {
                return _C2;
            }
            set
            {
                OnC2Changing(value);
                ReportPropertyChanging("C2");
                _C2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C2");
                OnC2Changed();
            }
        }
        private global::System.DateTime _C2;
        partial void OnC2Changing(global::System.DateTime value);
        partial void OnC2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C3
        {
            get
            {
                return _C3;
            }
            set
            {
                OnC3Changing(value);
                ReportPropertyChanging("C3");
                _C3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C3");
                OnC3Changed();
            }
        }
        private global::System.String _C3;
        partial void OnC3Changing(global::System.String value);
        partial void OnC3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> C4
        {
            get
            {
                return _C4;
            }
            set
            {
                OnC4Changing(value);
                ReportPropertyChanging("C4");
                _C4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C4");
                OnC4Changed();
            }
        }
        private Nullable<global::System.DateTime> _C4;
        partial void OnC4Changing(Nullable<global::System.DateTime> value);
        partial void OnC4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C5
        {
            get
            {
                return _C5;
            }
            set
            {
                OnC5Changing(value);
                ReportPropertyChanging("C5");
                _C5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C5");
                OnC5Changed();
            }
        }
        private global::System.String _C5;
        partial void OnC5Changing(global::System.String value);
        partial void OnC5Changed();

        #endregion

    
    }

    #endregion

    
}
